-- =============================================================================
-- FullSumppot — Professional account verification upgrade
-- Run once in Oracle SQL Developer (FULLSUMPOT schema)
-- =============================================================================

-- 1. Separate email / phone verification flags
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD IS_EMAIL_VERIFIED NUMBER(1) DEFAULT 0 NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD IS_PHONE_VERIFIED NUMBER(1) DEFAULT 0 NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD PRIMARY_CONTACT_TYPE VARCHAR2(10) DEFAULT ''EMAIL'' NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- Backfill: existing verified users had email verified
UPDATE USERS SET IS_EMAIL_VERIFIED = 1 WHERE IS_VERIFIED = 1 AND IS_EMAIL_VERIFIED = 0;
UPDATE USERS SET IS_PHONE_VERIFIED = 1
WHERE IS_VERIFIED = 1 AND PHONE_NUMBER IS NOT NULL AND IS_PHONE_VERIFIED = 0;

-- 2. OTP brute-force protection
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_OTPS ADD WRONG_ATTEMPTS NUMBER(3) DEFAULT 0 NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_OTPS ADD CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PHONE_OTPS ADD WRONG_ATTEMPTS NUMBER(3) DEFAULT 0 NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- 3. Secondary emails (one account, many emails — Instagram/Google style)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE USER_EMAILS (
            USER_EMAIL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            USER_ID       NUMBER NOT NULL,
            EMAIL         VARCHAR2(254) NOT NULL,
            IS_PRIMARY    NUMBER(1) DEFAULT 0 NOT NULL,
            IS_VERIFIED   NUMBER(1) DEFAULT 0 NOT NULL,
            CREATED_AT    TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
            CONSTRAINT FK_USER_EMAILS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
            CONSTRAINT UQ_USER_EMAILS_EMAIL UNIQUE (EMAIL)
        )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Seed primary emails for existing users
INSERT INTO USER_EMAILS (USER_ID, EMAIL, IS_PRIMARY, IS_VERIFIED)
SELECT u.USER_ID, LOWER(u.EMAIL), 1, u.IS_EMAIL_VERIFIED
FROM USERS u
WHERE NOT EXISTS (
    SELECT 1 FROM USER_EMAILS ue
    WHERE ue.USER_ID = u.USER_ID AND LOWER(ue.EMAIL) = LOWER(u.EMAIL)
);

-- 4. Auth audit log
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE AUTH_EVENTS (
            EVENT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            USER_ID    NUMBER,
            EVENT_TYPE VARCHAR2(50) NOT NULL,
            DETAIL     VARCHAR2(500),
            CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
        )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- 5. Normalize phone numbers to 10 digits
UPDATE USERS
SET PHONE_NUMBER = CASE
    WHEN PHONE_NUMBER IS NULL THEN NULL
    WHEN LENGTH(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '')) = 12
         AND REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '') LIKE '91%'
        THEN SUBSTR(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', ''), 3)
    WHEN LENGTH(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '')) = 11
         AND REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '') LIKE '0%'
        THEN SUBSTR(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', ''), 2)
    ELSE REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '')
END
WHERE PHONE_NUMBER IS NOT NULL;

COMMIT;

SELECT USER_ID, EMAIL, PHONE_NUMBER, IS_VERIFIED, IS_EMAIL_VERIFIED, IS_PHONE_VERIFIED
FROM USERS ORDER BY USER_ID;
