-- Normalize existing phone numbers to 10-digit format (no +91 prefix)
UPDATE USERS
SET PHONE_NUMBER = CASE
    WHEN PHONE_NUMBER IS NULL THEN NULL
    WHEN LENGTH(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '')) = 12
         AND REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '') LIKE '91%'
        THEN SUBSTR(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', ''), 3)
    WHEN LENGTH(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '')) = 11
         AND REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '') LIKE '0%'
        THEN SUBSTR(REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', ''), 2)
    ELSE REGEXP_REPLACE(PHONE_NUMBER, '[^0-9]', '')
END
WHERE PHONE_NUMBER IS NOT NULL;

COMMIT;

-- Check which accounts have a phone saved
SELECT USER_ID, USERNAME, EMAIL, PHONE_NUMBER, IS_VERIFIED FROM USERS ORDER BY USER_ID;
