UPDATE USERS SET IS_VERIFIED = 1 WHERE EMAIL = 'piyushchavan100@gmail.com';
COMMIT;
SELECT USERNAME, EMAIL, PHONE_NUMBER, IS_VERIFIED, ROLE FROM USERS WHERE EMAIL = 'piyushchavan100@gmail.com';
EXIT;
