using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;
using FullSummpotAPI.Data;
using Microsoft.AspNetCore.Authorization;

namespace FullSummpotAPI.Controllers
{
    /// <summary>
    /// One-time DDL setup endpoints. Secured behind [Authorize] so only
    /// authenticated admins can call them. Remove or disable in production.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class DatabaseInitController : ControllerBase
    {
        private readonly OracleDbContext _db;

        public DatabaseInitController(OracleDbContext db)
        {
            _db = db;
        }

        [HttpPost("setup-social")]
        public IActionResult SetupSocial()
        {
            using var conn = _db.GetConnection();
            conn.Open();

            try
            {
                // LINK_LIKES
                new OracleCommand(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE LINK_LIKES (
                        LIKE_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        LINK_ID   NUMBER NOT NULL,
                        USER_ID   NUMBER NOT NULL,
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT FK_LIKE_LINK FOREIGN KEY (LINK_ID) REFERENCES LINKS(LINK_ID) ON DELETE CASCADE,
                        CONSTRAINT FK_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
                        CONSTRAINT UNIQUE_LIKE UNIQUE(LINK_ID, USER_ID)
                    )';
                EXCEPTION WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN RAISE; END IF;
                END;", conn).ExecuteNonQuery();

                // LINK_COMMENTS
                new OracleCommand(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE LINK_COMMENTS (
                        COMMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        LINK_ID    NUMBER NOT NULL,
                        USER_ID    NUMBER NOT NULL,
                        CONTENT    VARCHAR2(1000) NOT NULL,
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT FK_COMMENT_LINK FOREIGN KEY (LINK_ID) REFERENCES LINKS(LINK_ID) ON DELETE CASCADE,
                        CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
                    )';
                EXCEPTION WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN RAISE; END IF;
                END;", conn).ExecuteNonQuery();

                return Ok(new { message = "Social tables initialized successfully" });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = ex.Message });
            }
        }
    }
}
